config/routes.rb
Jjfitness::Application.routes.draw do

	match 'fees/search_member' => 'fees#search_member'
	match 'members/show_paids' => 'members#show_paids'

  resources :fees

  resources :members

	resources :users

	get "account/register"

	get "account/change_pwd"

	get "account/index"

	get "account/login"

	resources :account do
		collection do
			get 'login'
		end
	end
  
  match "account/authenticate_user" => "account#authenticate_user", :as => "user_auth"
  

   match ':controller(/:action(/:id(.:format)))'
end

app/models/fee.rb
class Fee < ActiveRecord::Base
	belongs_to :member
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
	before_filter :confirm_logged_in
  # GET /fees
  # GET /fees.xml
  def index
    @fees = Fee.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fees }
    end
  end

  # GET /fees/1
  # GET /fees/1.xml
  def show
    @fee = Fee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fee }
    end
  end

  # GET /fees/new
  # GET /fees/new.xml
  def new
    @fee = Fee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fee }
    end
  end

  # GET /fees/1/edit
  def edit
    @fee = Fee.find(params[:id])
  end

  # POST /fees
  # POST /fees.xml
  def create
    @fee = Fee.new(params[:fee])
		
    respond_to do |format|
      if @fee.save
      @fee.member.last_paid = Date.today
      @fee.member.save
        format.html { redirect_to(@fee, :notice => 'Fee was successfully created.') }
        format.xml  { render :xml => @fee, :status => :created, :location => @fee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fees/1
  # PUT /fees/1.xml
  def update
    @fee = Fee.find(params[:id])

    respond_to do |format|
      if @fee.update_attributes(params[:fee])
        format.html { redirect_to(@fee, :notice => 'Fee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.xml
  def destroy
    @fee = Fee.find(params[:id])
    @fee.destroy

    respond_to do |format|
      format.html { redirect_to(fees_url) }
      format.xml  { head :ok }
    end
  end
  
  def search_member
  	@member = Member.search(params[:membership_number]).first
	respond_to do |format|
	  format.js
	end

  end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_form.html.erb
<% form_tag url_for(:action => "search_member"), :remote=>true do %>
  <p>
  	<%= label_tag :membership_number %><br />
    <%= search_field_tag :membership_number %>
    <%= submit_tag("Search", :disable_with=> "please wait...") %>
  </p>
<% end %>

<%= form_for(@fee) do |f| %>
  <% if @fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
      <% @fee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :member_id %>
  
  <div class="field">
    <%= label_tag :member_name %><br />
    <%= text_field_tag :member_name, "", :disabled => true %>
    <%= label_tag "Last Paid" %>
    <%= text_field_tag :last_paid, "", :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.date_select :from,  :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    
    <%= f.date_select :to, :order => [:day, :month, :year], :default => 30.days.from_now %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :advance %><br />
    <%= f.text_field :advance %>
  </div>
  <div class="field">
    <%= f.label :pending %><br />
    <%= f.text_field :pending %>
  </div>
  <div class="field">
    <%= f.label :proprietor %><br />
    <%= f.text_field :proprietor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing fee</h1>

<%= render 'form' %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<h1>Listing fees</h1>

<table>
  <tr>
    <th>Member</th>
    <th>From</th>
    <th>To</th>
    <th>Amount</th>
    <th>Advance</th>
    <th>Pending</th>
    <th>Proprietor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fees.each do |fee| %>
  <tr>
    <td><%= fee.member_id %></td>
    <td><%= fee.from %></td>
    <td><%= fee.to %></td>
    <td><%= fee.amount %></td>
    <td><%= fee.advance %></td>
    <td><%= fee.pending %></td>
    <td><%= fee.proprietor %></td>
    <td><%= link_to 'Show', fee %></td>
    <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
    <td><%= link_to 'Destroy', fee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New fee</h1>

<%= render 'form' %>

<%= link_to 'Back', fees_path %>

app/views/fees/search_member.js.erb
document.ready = setValues();

function setValues(){
alert("<%= @member.class %>");
	<% unless @member.nil? %>
		document.getElementById("member_name").value = "<%= @member.name %>";
		document.getElementById("fee_member_id").value = <%= @member.id %>;
		<% if @member.last_paid.nil? %>
		document.getElementById("last_paid").value = "";
		<% else %>
		document.getElementById("last_paid").value = "<%= @member.last_paid.strftime('%d %B %Y') %>";
		<% end %>
	<% else %>
		document.getElementById("member_name").value = "";
		document.getElementById("fee_member_id").value ="";
		document.getElementById("last_paid").value = "";
	<% end %>
}

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @fee.member_id %>
</p>

<p>
  <b>From:</b>
  <%= @fee.from %>
</p>

<p>
  <b>To:</b>
  <%= @fee.to %>
</p>

<p>
  <b>Amount:</b>
  <%= @fee.amount %>
</p>

<p>
  <b>Advance:</b>
  <%= @fee.advance %>
</p>

<p>
  <b>Pending:</b>
  <%= @fee.pending %>
</p>

<p>
  <b>Proprietor:</b>
  <%= @fee.proprietor %>
</p>


<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>