config/routes.rb
Jjfitness::Application.routes.draw do

	match 'fees/search_member' => 'fees#search_member'
	match 'members/show_paids' => 'members#show_paids'

  resources :fees

  resources :members

	resources :users

	get "account/register"

	get "account/change_pwd"

	get "account/index"

	get "account/login"

	resources :account do
		collection do
			get 'login'
		end
	end
  
  match "account/authenticate_user" => "account#authenticate_user", :as => "user_auth"
  

   match ':controller(/:action(/:id(.:format)))'
end

app/models/member.rb
class Member < ActiveRecord::Base
 	scope :search, lambda{|query| where("memership_number = #{query}")}
 	scope :fees_paid, where("last_paid between '#{Date.today.at_beginning_of_month
}' and '#{Date.today}'")
	scope :this_month_admissions, where("created_at > '#{Date.today.at_beginning_of_month
}'")
 	has_many :fees
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	
	before_filter :confirm_logged_in

  # GET /members
  # GET /members.xml
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new
    @last_member = Member.last    

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.xml
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to(@member, :notice => 'Member was successfully created.') }
        format.xml  { render :xml => @member, :status => :created, :location => @member }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
  
  def show_paids
  	@members = Member.fees_paid
  	@new_members = Member.this_month_admissions
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :memership_number %><br />
    <% if @last_member.nil? %>
	    <%= f.text_field :memership_number %>
    <% else %>
    	    <%= f.text_field :memership_number, :value=> "#{@last_member.memership_number + 1}" %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :blood_group %><br />
    <%= f.text_field :blood_group %>
  </div>
  <div class="field">
    <%= f.label :profession %><br />
    <%= f.text_field :profession %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, :size => "36x4" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Memership number</th>
    <th>Name</th>
    <th>Age</th>
    <th>Blood group</th>
    <th>Profession</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.memership_number %></td>
    <td><%= member.name %></td>
    <td><%= member.age %></td>
    <td><%= member.blood_group %></td>
    <td><%= member.profession %></td>
    <td><%= member.address %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Memership number:</b>
  <%= @member.memership_number %>
</p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Age:</b>
  <%= @member.age %>
</p>

<p>
  <b>Blood group:</b>
  <%= @member.blood_group %>
</p>

<p>
  <b>Profession:</b>
  <%= @member.profession %>
</p>

<p>
  <b>Address:</b>
  <%= @member.address %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/members/show_paids.html.erb
<h1> Fees paid this month:</h1>
<ul>
	<% 
		@members.each do |member|
	%>
	<%=raw "<li>Name: #{member.name}, Membership Number: #{member.memership_number}, Paid Date: #{member.last_paid}</li>" %>
	<%
		end
	%>
</ul>


<h1> This month new Admissions:</h1>
<ul>
	<% 
		@new_members.each do |new_member|
	%>
	<% if new_member.fees.length > 0 %>
	<%=raw "<li>Name: #{new_member.name}, Membership Number: #{new_member.memership_number}, Join Date: #{new_member.created_at.strftime("%d - %m - %Y")}, Paid: #{new_member.fees.first.advance + new_member.fees.first.amount}, Balance: #{new_member.fees.first.pending} </li>" %>
	<% else %>
	<%=raw "<li>Name: #{new_member.name}, Membership Number: #{new_member.memership_number}, Join Date: #{new_member.created_at.strftime("%d - %m - %Y")}, Paid: -nil-, Balance: -nil- </li>" %>
	<% end %>
	
	<%
		end
	%>
</ul>